# horizontal-pod-scaler.yaml

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    phase: {{ .Values.label.phase }}
spec:
  maxReplicas: {{ .Values.horizontalPodAutoscaler.maxReplicas }}
  minReplicas:  {{ .Values.horizontalPodAutoscaler.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}