#service.yaml

apiVersion: v1
kind: Service
metadata:
  namespace: workshop
  name: node-hello-world
  labels:
    phase: toi
spec:
  type:  ClusterIP
  selector:
    app: node-hello-world
    phase: toi
  ports:
    - port: 8000
      name: node-hello-world-port
      protocol: TCP
      targetPort: 8000