#dev-values.yaml

app:
  name: node-hello-world

image:
  repository: docker.io/diorleoroy/nodejs-sample
  tag: v1

label:
  phase: toi

replicaCount: 1

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 150Mi


horizontalPodAutoscaler:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 60






